# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(blank=True, max_length=200, verbose_name='kind')),
                ('operation', models.CharField(blank=True, max_length=100, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('detail', models.TextField(blank=True, verbose_name='\u7ec6\u8282')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='PermitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit', models.TextField(default='[]', verbose_name='permit')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
            ],
        ),
    ]
