# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmodel',
            name='operation',
        ),
        migrations.AddField(
            model_name='logmodel',
            name='key',
            field=models.CharField(blank=True, max_length=200, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='kind',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u64cd\u4f5c\u7c7b\u578b'),
        ),
    ]
